version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: fraudx-api
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
    environment:
      - WORKERS=4

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: fraudx-frontend
    ports:
      - "5173:5173"
    depends_on:
      - api
